# Generated by Django 5.0.1 on 2024-04-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Return',
            new_name='ReturnObj',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='prod_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='pmt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mainwebsite.payment'),
        ),
    ]
